INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( '﻿mbac', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( '﻿mbac', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'jbar', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'jbar', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'ecol', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'ecol', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'jcra', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'jcra', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'jcri', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'jcri', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'jcri', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'jcri', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'mdeb', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'mdeb', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'gdec', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'gdec', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'aeid', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'aeid', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'menl', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'menl', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'gfau', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'gfau', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'agan', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'agan', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'jger', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'jger', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'agoo', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'agoo', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'ahay', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'ahay', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'ahei', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'ahei', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'shoo', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'shoo', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'bjhn', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'bjhn', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'rkau', 'fall22', NULL, '3', 'Second Year' );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'rkau', 'spr23', NULL, '3', 'Second Year' ) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'nkc', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'nkc', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'jket', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'jket', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'skle', 'fall22', NULL, '3', 'Second Year' );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'skle', 'spr23', NULL, '3', 'Second Year' ) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'nkuz', 'fall22', NULL, '3', 'visa travel?' );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'nkuz', 'spr23', NULL, '6', '' ) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'kale', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'kale', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'dlie', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'dlie', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'smac', 'fall22', NULL, '3', 'Second Year' );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'smac', 'spr23', NULL, '3', 'Second Year' ) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'amal', 'fall22', NULL, '3', 'Second Year' );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'amal', 'spr23', NULL, '3', 'Second Year' ) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'aman', 'fall22', NULL, '4', 'fall only' );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'aman', 'spr23', NULL, '0', 'conditional' ) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'mmar', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'mmar', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'dmck', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'dmck', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'smye', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'smye', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'nmey', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'nmey', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'smoo', 'fall22', NULL, '3', 'Second Year' );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'smoo', 'spr23', NULL, '3', 'Second Year' ) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'vmor', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'vmor', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'kmor', 'fall22', NULL, '3', 'fall only' );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'kmor', 'spr23', NULL, '0', 'not teaching' ) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'ymu ', 'fall22', NULL, '3', 'Second Year' );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'ymu ', 'spr23', NULL, '3', 'Second Year' ) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'smue', 'fall22', NULL, '3', 'Second Year' );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'smue', 'spr23', NULL, '3', 'Second Year' ) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'tmur', 'fall22', NULL, '3', 'Second Year' );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'tmur', 'spr23', NULL, '3', 'Second Year' ) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'amye', 'fall22', NULL, '3', 'Second Year' );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'amye', 'spr23', NULL, '3', 'Second Year' ) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'znas', 'fall22', NULL, '3', 'Second Year' );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'znas', 'spr23', NULL, '3', 'Second Year' ) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'jngu', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'jngu', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'lpai', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'lpai', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'mpiw', 'fall22', NULL, '3', 'Second Year' );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'mpiw', 'spr23', NULL, '3', 'Second Year' ) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'sros', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'sros', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'arow', 'fall22', NULL, '3', 'Second Year' );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'arow', 'spr23', NULL, '3', 'Second Year' ) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'isaf', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'isaf', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'josc', 'fall22', NULL, '3', 'Second Year' );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'josc', 'spr23', NULL, '3', 'Second Year' ) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'lsem', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'lsem', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'asot', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'asot', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'ktad', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'ktad', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'rtho', 'fall22', NULL, '3', 'Second Year' );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'rtho', 'spr23', NULL, '3', 'Second Year' ) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'kvan', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'kvan', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'mvan', 'fall22', NULL, '3', 'Second Year' );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'mvan', 'spr23', NULL, '3', 'Second Year' ) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'avo', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'avo', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'dwel', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'dwel', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'dwhi', 'fall22', NULL, '3', 'Second Year' );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'dwhi', 'spr23', NULL, '3', 'Second Year' ) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'mwic', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'mwic', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'awri', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'awri', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'fzim', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'fzim', 'spr23', NULL, '3', NULL) ;
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'cgod', 'fall22', NULL, '6', NULL );
INSERT INTO `schedule`.`teaching` ( `instructor`, `session`, `fte`, `crhr`, `comments` ) VALUES ( 'cgod', 'spr23', NULL, '3', NULL) ;
